Exercise 4
Systems-Development-and-Frameworks/bgrakia pull request #11
Opened 2020-12-04 16:18 UTC by MaykAkifovski

2020-12-04 16:23 UTC, MaykAkifovski commented
@Systems-Development-and-Frameworks/countryroads, there is a bug in our PR and we are not able to add you as a Code Reviewer. I have to manually go to our PR and make a code review.

2020-12-05 17:13 UTC, yiimnta commented
> @Systems-Development-and-Frameworks/countryroads, there is a bug in our PR and we are not able to add you as a Code Reviewer. I have to manually go to our PR and make a code review.

Hi...
when i can review your code, please add me.
if possible, can i review a bit before waiting for fixing your bug?

2020-12-06 20:26 UTC, yiimnta reviewed
Review on **12.06.2020** at commit "**tests fixed**(**1f1eb90**)"

The idea of using graph-shield to check the login (passwordIsValid) and to check the user has voted or not (isPostUpvoted) is quite good 👍 . And you can create 2 classes Post and User to give the code a more cool look. :wink:



✔️ ⭐ For an implemented signup feature.

❌ ⭐ For a software-tested signup feature.

✔️ ⭐ For password validation.

✔️ ⭐ For unique email address validation.

✔️ ⭐ For not having security issues according to instructions.

✔️ ⭐ For an implemented login feature using JWT.

❌ ⭐ For a software-tested login feature.

✔️ ⭐ For assigning the authenticated user to a post in write and upvote mutations.

✔️ ⭐ For requesting a review and reviewing another team's PR according to the instructions.

❌ ⭐ For a successful rebase on homework/main.

2020-12-06 20:26 UTC, yiimnta commented on backend/src/resolvers.js
>          };
If you return a name like this then it's not possible to nest your queries 'indefinitely':

``` graphql
{
   posts {
     title
     votes
     author {
       name
       posts {
         title
       }
     }
   }
}
```
as result, the author's posts will be an empty list.
Here you should return to a User instead of the author's name.

```suggestion
return await dataSources.usersApi.getUserById(parent.author);
```

2020-12-06 20:26 UTC, yiimnta commented on backend/src/tests/tests.test.js
> +    });
1/2⭐ For assigning the authenticated user to a post in **write** mutations.

2020-12-06 20:26 UTC, yiimnta commented on backend/src/tests/tests.test.js
>      });
1/2⭐ For assigning the authenticated user to a post in **_upvote_** mutations.

2020-12-06 20:26 UTC, yiimnta commented on backend/src/resolvers.js
>        }
⭐ For an implemented login feature using JWT.

2020-12-06 20:26 UTC, yiimnta commented on backend/src/resolvers.js
> +      },
⭐ For an implemented signup feature.

2020-12-06 20:26 UTC, yiimnta commented on backend/src/security/permissions.js
> +        not(emailIsTaken, new UserInputError("A user with this email already exists.")),
⭐ For unique email address validation.

2020-12-06 20:26 UTC, yiimnta commented on backend/src/security/permissions.js
> +        not(passwordIsTooShort, new UserInputError("The password must be at least 8 characters long."))
⭐ For password validation.

2020-12-06 20:26 UTC, yiimnta commented on backend/src/tests/tests.test.js
> +const contextPipeline = () => context({ req: reqMock, res: resMock });
you could easily use:

```javascript
const contextPipeline = () => {}
```

when you want to authenticate a user, just use:

```javascript
server.context = () => ({token: {uId: user_id}});
```

instead of creating these variables:

```javascript
reqMock = { headers: {} };
resMock = {};

let userIds = [uuidv4(), uuidv4()];

mike_auth_token = await authApi.createToken(userIds[0]);
atanas_auth_token = await authApi.createToken(userIds[1]);
```

2020-12-06 20:26 UTC, yiimnta commented on backend/src/tests/tests.test.js
>              query {
try testing the following query and you will see that the author's posts list will be empty.

```javascript
const GET_POSTS = gql`
            query {
                    posts {
                        title
                        author {
                            name
                            posts {
                                title
                                author {
                                    name
                                }
                            }
                        }
                    }
                }`;
```

2020-12-10 22:03 UTC, roschaefer requested changes
![not bad](https://media.giphy.com/media/13ZHjidRzoi7n2/giphy.gif)

Yes, I agree with @yiimnta here. You achieved 7/10 :stars: well done!

What got me the most is that you have put so much logic (also data-validations) into the permissions layer.

See my suggestions below.

2020-12-10 22:03 UTC, roschaefer commented on backend/src/context.js
> +        const decodedToken = jwt.verify(token, process.env.JWT_SECRET);
I would suggest to import a file here wich `require('dotenv')` and exports a constant `JWT_SECRET`. You would avoid a `process.env.JWT_SECRET` being undefined here, regardless of the order how files are loaded.

2020-12-10 22:03 UTC, roschaefer commented on backend/src/datasources/authenticationApi.js
> +        return jwt.sign({ uId: userId }, process.env.JWT_SECRET, { algorithm: 'HS256', expiresIn: '1h' });
`expiresIn` :+1:

2020-12-10 22:03 UTC, roschaefer commented on backend/src/datasources/userApi.js
> +    return this.users.find(user => user.id == id);
```suggestion
    return this.users.find(user => user.id === id);
```

2020-12-10 22:03 UTC, roschaefer commented on backend/src/datasources/userApi.js
> +    return this.users.find(user => user.email == email);
```suggestion
    return this.users.find(user => user.email === email);
```

2020-12-10 22:03 UTC, roschaefer commented on backend/src/datasources/userApi.js
> +    let obj = {id: uuidv4(), name: name, email: email, posts: [], password: await this.hashPassword(password)};
Put that into a `User` constructor. It's obviously a creator function.

2020-12-10 22:03 UTC, roschaefer commented on backend/src/datasources/userApi.js
> +    const saltRounds = parseInt(process.env.SALT_ROUNDS);
Make that a constant

2020-12-10 22:03 UTC, roschaefer commented on backend/src/security/permissions.js
> +      email: and(isAuthenticated, canSeeEmail),
You got a :rocket: 
>  :rocket: For authorizing read access on `User.email`:
> Allows access only if `email` belongs to authenticated user.

2020-12-10 22:03 UTC, roschaefer commented on backend/src/security/permissions.js
> +        not(emailIsTaken, new UserInputError("A user with this email already exists.")),
Interesting, didn't know that `not` has a second `error` argument.

2020-12-10 22:03 UTC, roschaefer commented on backend/src/resolvers.js
>          };
That's 100% correct!

2020-12-10 22:03 UTC, roschaefer commented on backend/src/security/permissions.js
> +        not(passwordIsTooShort, new UserInputError("The password must be at least 8 characters long.")),
```suggestion
```
That shouldn't be necessary on `login` :thinking:

2020-12-10 22:03 UTC, roschaefer commented on backend/src/security/permissions.js
> +        // This may look strange, but if an already authenticated user authenticates (logs in) a second time, she'll have two tokens! This is not good practice.
Why is this a problem? :thinking:

2020-12-10 22:03 UTC, roschaefer commented on backend/src/security/permissions.js
> +        not(isAuthenticated, new Error("Already logged in. Redirect to home page.")),
You would implement a redirect in the frontend, not the backend.

2020-12-10 22:03 UTC, roschaefer commented on backend/src/security/permissions.js
> +        not(isPostWithTitlePresent, new UserInputError("Post with this title already exists."))
From my point of view, data validations like this shouldn't be part of your permission matrix.

2020-12-10 22:03 UTC, roschaefer commented on backend/src/security/rules.js
> +        const user = await dataSources.usersApi.getUserById(token.uId);
:+1: 
>   * Specific to our use-case: Make sure a JWT is only valid if a corresponding user in the database exists. The user might have been deleted or disabled since the JWT was issued.

2020-12-10 22:03 UTC, roschaefer commented on backend/src/security/rules.js
> +const canSeeEmail = rule({ cache: 'strict' })(
You could call this `isMe` or `isAuthenticatedUser` and re-use that for fields other than `email`.

2020-12-10 22:03 UTC, roschaefer commented on backend/src/security/rules.js
> +const passwordIsTooShort = rule({ cache: 'strict' })(
I consider this as data-validation, so it shouldn't be part of `permission` middleware.

2020-12-10 22:03 UTC, roschaefer commented on backend/src/security/rules.js
> +const passwordIsValid = rule({ cache: 'strict' })(
Also this logic should go into the `login` resolver itself.

2020-12-10 22:03 UTC, roschaefer commented on backend/src/security/rules.js
> +        }
You have this if-clause because you re-use this rule for different mutations with different `args`. I think this is sub-optimal, better move this logic into the resolver.

2020-12-10 22:03 UTC, roschaefer commented on backend/src/security/rules.js
> +const isPostUpvoted = rule({ cache: 'strict'})(
This code should be as close to the `Post` class as possible, so this gets checked not only during a GraphQL request execution

2020-12-10 22:03 UTC, roschaefer commented on backend/src/security/rules.js
> +exports.canSeeEmail = canSeeEmail;
Use ES6 imports or `exports = { isAuthenticated, isPostUpvoted, isPostWithTitlePresent, /* ... */ }`

2020-12-10 22:03 UTC, roschaefer commented on backend/src/tests/tests.test.js
> +const schema = applyMiddleware(
I would suggest to put that into a file that gets imported in your production code as well as your tests.

2020-12-10 22:03 UTC, roschaefer commented on backend/src/tests/tests.test.js
> +const contextPipeline = () => context({ req: reqMock, res: resMock });
Yes, mocking the `context` is fine and it's how I implemented the tests in my reference solution. However, this is copied from my [example code](https://github.com/apollographql/apollo-server/issues/2277#issuecomment-737497337) for people who really want to test the requests headers for whatever reason.

2020-12-10 22:03 UTC, roschaefer commented on backend/src/tests/tests.test.js
> +    process.env.JWT_SECRET='TEST_SECRET';
```suggestion
```
Please do not write `process.env` in JavaScript. You could use `dotenv-flow` and put a non-secret into version control.

2020-12-10 22:03 UTC, roschaefer commented on backend/src/tests/tests.test.js
> +        { title: "Atanas's Post 2", votes: 0, upvoters:[], author: userIds[1] },
```suggestion
        new Post({ title: "Mike's Post 1", author: userIds[0] }),
        new Post({ title: "Mike's Post 2", author: userIds[0] }),
        new Post({ title: "Atanas's Post 1", author: userIds[1] }),
        new Post({ title: "Atanas's Post 2", author: userIds[1] }),
```
This could be DRYed with a class.

2020-12-10 22:03 UTC, roschaefer commented on backend/src/tests/tests.test.js
> +            posts: postsApi.posts.slice(0, 2)
Why do you have bi-directional reference for a 1:m relationship? Adding redundancy leads to errors.

2020-12-10 22:03 UTC, roschaefer commented on backend/src/tests/tests.test.js
> +    it("creates new post - not authenticated", async () => {
```suggestion
    it("creates no post - not authenticated", async () => {
```

2020-12-14 14:53 UTC, merged

2020-12-14 15:19 UTC, ubiquitousbyte commented
@roschaefer We've actually implemented both software testing for the signup function, as well as for the login function. Do you mind explaining why we've lost the stars?